### ISSUE TITLE
AdvancedFilters should use a smaller rectangle for image analysis

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/resizer#118]
Rounding differences can cause padding to still be slightly involved in histogram calculation, as the differing results for these two requests show.

/tulip-leaf.jpg?maxwidth=300&a.balancewhite=true&paddingWidth=100&srotate=90
/tulip-leaf.jpg?maxwidth=300&a.balancewhite=true&paddingWidth=100&rotate=90

This means we need to shrink the analysis rectangle by at least one pixel in order to compensate - for we still need to apply the resulting operations to the inclusive whole.

**Comment by lilith** [comment]
Can no longer reproduce now that AdvancedFilters rounds rectangles in shrink mode.
