### ISSUE TITLE
Create nuget packages for Faces + RedEye

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/resizer#123]
RedEye depends on Faces.

**Comment by tostercx** [comment]
I don't see the version of OpenCV we use on nuget. Should it be packed with the plugin?

**Comment by nathanaeljones** [comment]
The wrapper, OpenCvSharp, could be referenced as a dependency. We should upgrade to the latest opencv version it supports. https://www.nuget.org/packages/OpenCvSharp-AnyCPU/

**Comment by tostercx** [comment]
Added:
14757378be60907f30289c316ee355e141c0240f
36b4ca96aa850967bd58840c697036c9770d4cbc
