### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by villanus** [imazen/resizer#131]
I am testing your plugin with S3 reader.  It just works without a lic.  Is this normal behavior, or should I be purchasing a lic somewhere for local testing and dev.

If we move forward, how do we install a lic?

**Comment by nathanaeljones** [comment]
It's currently on the honor system, no DRM. To comply with copyright law, however, you will need to buy a license from http://imageresizing.net once you begin using it on a production server.

**Comment by villanus** [comment]
Thanks!  Everything is working great for us, and once in production I will make sure to get a lic.
