### ISSUE TITLE
ImageResizer.Util.BundleAttribute fails to load

### ISSUE THREAD

**Issue by Otto404** [imazen/resizer#143]
I need a hint ! 

Serverfehler in der Anwendung /.

Der Typ "ImageResizer.Util.BundleAttribute" in der Assembly "ImageResizer, Version=3.0.9.20805, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden. 
  Beschreibung: Unbehandelte Ausnahme beim Ausführen der aktuellen Webanforderung. Überprüfen Sie die Stapelüberwachung, um weitere Informationen über diesen Fehler anzuzeigen und festzustellen, wo der Fehler im Code verursacht wurde. 

 Ausnahmedetails: System.TypeLoadException: Der Typ "ImageResizer.Util.BundleAttribute" in der Assembly "ImageResizer, Version=3.0.9.20805, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden.

Quellfehler: 

 Beim Ausführen der aktuellen Webanforderung wurde einen unbehandelte Ausnahme generiert. Informationen über den Ursprung und die Position der Ausnahme können mit der Ausnahmestapelüberwachung angezeigt werden.  

Stapelüberwachung: 

[TypeLoadException: Der Typ "ImageResizer.Util.BundleAttribute" in der Assembly "ImageResizer, Version=3.0.9.20805, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden.]
   System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr\* typeInstArgs, Int32 typeInstCount, IntPtr\* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type) +0
   System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) +145
   System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) +158
   System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg) +91
   System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent) +438
   System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType) +103
   System.Reflection.RuntimeAssembly.GetCustomAttributes(Boolean inherit) +37
   Owin.Loader.DefaultLoader.SearchForStartupAttribute(String friendlyName, IList`1 errors, Boolean& conflict) +106
   Owin.Loader.DefaultLoader.GetDefaultConfiguration(String friendlyName, IList`1 errors) +46
   Owin.Loader.DefaultLoader.LoadImplementation(String startupName, IList`1 errorDetails) +75
   Owin.Loader.DefaultLoader.Load(String startupName, IList`1 errorDetails) +21
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.GetAppStartup() +115
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +28
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +115
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +106
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +534
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +352
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): Der Typ "ImageResizer.Util.BundleAttribute" in der Assembly "ImageResizer, Version=3.0.9.20805, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9940016
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

Versionsinformationen: Microsoft .NET Framework-Version:4.0.30319; ASP.NET-Version:4.6.57.0

**Comment by lilith** [comment]
Don't use a 2011 alpha version of ImageResizer with 2014/2015 versions of plugins for it. Make sure all ImageResizer\* dlls are from the same release.

**Comment by Otto404** [comment]
Update worked.
