### ISSUE TITLE
DiskCache does not cache when source is AzureReader2 and there are no request parameters

### ISSUE THREAD

**Issue by danielcrenna** [imazen/resizer#145]
If in AzureReader2 your config lists `redirectToBlobIfUnmodified="false"` (which would be required currently if you wanted to serve private azure source files without modification), and you use DiskCache, it is bypassed. If you fetch the same file with width=n (where n is the full width of the image or greater), then the full source image is cached as expected.

It would be ideal if no-op image requests to resizer were cached to disk in this scenario.

(V4 nightlies)

**Comment by lilith** [comment]
This is controlled by[ `cacheUnmodifiedFiles="false"`](http://imageresizing.net/docs/v4/plugins/azurereader2#configuration-reference).
