### ISSUE TITLE
DiskCache config is not accepting arguments

### ISSUE THREAD

**Issue by danielcrenna** [imazen/resizer#146]
When using DiskCache, and you pass any arguments in plugin config (i.e. `subfolders`) you get this error in `resizer.debug`:

`Plugins(ConfigurationError):   The plugin ImageResizer.Plugins.DiskCache.DiskCache doesn't support constructor arguments. To support arguments in the <add> element, the plugin must have a public constructor that accepts a NameValueCollection argument.`

(V4, nightlies)

**Comment by lilith** [comment]
The error message is correct; you're placing the attributes in the wrong XML element. `<diskcache>` is a separate node within `<resizer>`.

**Comment by danielcrenna** [comment]
Sorry for the derp noise.

On Tue, Jul 7, 2015 at 9:29 AM, Nathanael Jones notifications@github.com
wrote:

> The error message is correct; you're placing the attributes in the wrong
> XML element. <diskcache> is a separate node within <resizer>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/imazen/resizer/issues/146#issuecomment-119202611.

## 

Daniel Crenna
Conatus Creative Inc.
cell:613.400.4286
