### ISSUE TITLE
Update S3Reader plugin to AWS SDK v3

### ISSUE THREAD

**Issue by sixten** [imazen/resizer#148]
At long last, [Amazon has broken up their monolithic .NET SDK into service-specific chunks](http://blogs.aws.amazon.com/net/post/Tx2LYP1E6UUTVXN/Version-3-of-the-AWS-SDK-for-NET-Out-of-Preview), substantially reducing the weight of the dependency for applications that only use a few of their services. It would be great to update the S3Reader plugin's dependencies so that any projects using it can be upgraded in their turn.

**Comment by aviatrix** [comment]
@nathanaeljones i think you can close this :)
