### ISSUE TITLE
Native dependency downloading model is broken

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/resizer#15]
The current plugin loading model permits other imageresizer requests to continue before plugin loading is complete. This causes failed requests for S3, remote urls. 

Also, this permits file locking issues when large numbers of native dependencies are being downloaded.

Resolution is to force a gateway, so no requests can proceed until all plugins are installed.

**Comment by lilith** [comment]
.NET Core promises to fix this scenario (eventually), at which point a polyfill for .NET full would be reasonable to implement.
