### ISSUE TITLE
Resizer stops working randomly, only app pool recycle helps

### ISSUE THREAD

**Issue by filipw** [imazen/resizer#150]
Hi

We are running the following configuration:
- IIS Root App has it's own image resizer in the web.config (v 3.4.3.103)
- There is a child app under that root app, which removes the resizer module and uses "its own" configuration. The DLL version there is v 3.4.1.474

Image Resizer in the child application works fine for a while but stops working randomly after a few hours with the following stacktrace:

```
[ExternalException (0x80004005): A generic error occurred in GDI+.]
   System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams) +768497
   ImageResizer.ImageBuilder.buildToStream(Bitmap source, Stream dest, ResizeSettings settings) +176
   ImageResizer.ImageBuilder.BuildJob(ImageJob job) +1353
   ImageResizer.ImageBuilder.Build(ImageJob job) +268
   ImageResizer.ImageBuilder.Build(Object source, Object dest, ResizeSettings settings, Boolean disposeSource, Boolean addFileExtension) +124
   ImageResizer.ImageBuilder.Build(Object source, Object dest, ResizeSettings settings, Boolean disposeSource) +36
   ImageResizer.ImageBuilder.Build(Object source, Object dest, ResizeSettings settings) +23
   ImageResizer.&lt;&gt;c__DisplayClass3.&lt;HandleRequest&gt;b__2(Stream stream) +280
   ImageResizer.Plugins.DiskCache.&lt;&gt;c__DisplayClass5.&lt;GetCachedFile&gt;b__0() +474
   ImageResizer.Plugins.DiskCache.LockProvider.TryExecute(String key, Int32 timeoutMs, LockCallback success) +424
   ImageResizer.Plugins.DiskCache.CustomDiskCache.GetCachedFile(String keyBasis, String extension, ResizeImageDelegate writeCallback, DateTime sourceModifiedUtc, Int32 timeoutMs, Boolean asynchronous) +1047
   ImageResizer.Plugins.DiskCache.DiskCache.Process(IResponseArgs e) +209
   ImageResizer.Plugins.DiskCache.DiskCache.Process(HttpContext context, IResponseArgs e) +47
   ImageResizer.InterceptModule.HandleRequest(HttpContext context, String virtualPath, NameValueCollection queryString, IVirtualFile vf) +1652
   ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest(Object sender, EventArgs e) +1163
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +92
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +165
```

Only app pool recycle restores the resizer functionality.
Moreover, we are only observing this issue on one server. Any tips, suggestions?

The config is pretty standard:

```
      <resizer>
        <plugins>
          <add name="DiskCache" />
        </plugins>
        <sizelimits imageWidth="0" imageHeight="0" totalWidth="3200" totalHeight="3200" totalBehavior="throwexception" />
        <diskCache dir="~/imagecache" autoClean="true" hashModifiedDate="true" enabled="true" subfolders="256" cacheAccessTimeout="15000" asyncWrites="true" asyncBufferSize="10485760" />
        <cleanupStrategy startupDelay="00:05" minDelay="00:00:20" maxDelay="00:05" optimalWorkSegmentLength="00:00:04" targetItemsPerFolder="400" maximumItemsPerFolder="1000" avoidRemovalIfCreatedWithin="24:00" avoidRemovalIfUsedWithin="4.00:00" prohibitRemovalIfUsedWithin="00:05" prohibitRemovalIfCreatedWithin="00:10" />
      </resizer>
```

**Comment by filipw** [comment]
note that when this happens, none of the images can be resized anymore - it's not image specific

**Comment by lilith** [comment]
Are there any other symptoms (increased memory use, failed disk writes, permissions issues with the triggering file)?

**Comment by filipw** [comment]
I will try to gather some more data and post here, thanks for the quick response.

BTW, I take back what I just said - **it is file specific**, so some images can still be resized, while others start failing, which suggests this is some sort of a DiskCache problem (or maybe even the underlying disk itself)

**Comment by lilith** [comment]
v4 leverages the improved filesystem APIs included in .NET 4.5 to marginally reduce concurrency issues. That said, there's no known bug in DiskCache 3.4.3 with the default cleanup settings. I'd drop `<cleanupStrategy/>` to ensure everything is at its efaults. 

Are there more than 80k files in the /imagecache/ directory?

**Comment by mbohatkiewicz** [comment]
The memory use according to the client is normal: '40% memory usage and 3% CPU'

/imagecache dir has at least several MBs worth of files

**Comment by lilith** [comment]
So there are fewer than 80,000 unique files in the directory? If so, it's unlikely to be associated with disk cleanup (although that's easy to prove - set `autoClean=false`).

**Comment by mbohatkiewicz** [comment]
The child app is running imageresizer DLLs version 3.4.1. Are there any know issues with this version?

**Comment by lilith** [comment]
Mostly around watermarking. http://imageresizing.net/releases/3-4-3

**Comment by lilith** [comment]
Hi @filiw, if you still haven't been able to reproduce this on a different server, I'm going to guess that this is a hardware or filesystem problem.

If you get any information that suggests otherwise, let me know and I will re-open this issue.
