### ISSUE TITLE
400 Bad request with AzureReader2

### ISSUE THREAD

**Issue by rohandesouza** [imazen/resizer#152]
The AzureReader2 gives me a 400 Bad request error when I try to load the page. However if I turn the AzureReader2 plugin off and browse the page with this plugin turned off and then turn the plugin after browsing the page works fine and loads images as expected. 

Can't seem to figure out what's causing this bug. 
(Example: http://iwkwestcoastus.azurewebsites.net/Default.aspx) This page works fine because it has been browsed before AzureReader2 is turned on. All other pages show up with a 400 Bad request error.

**Comment by lilith** [comment]
https://stackoverflow.com/questions/30997148/azurereader2-gives-me-a-400-bad-request-when-enabled/31003459?noredirect=1#comment50870020_31003459
