### ISSUE TITLE
Crop start point

### ISSUE THREAD

**Issue by mhelaiwa** [imazen/resizer#156]
How to specify the x and y for crop inside settings object?

```
var settings = new ResizeSettings()
{

    Width = 50,
    Height = 50,
    Mode = FitMode.Crop
};
ImageResizer.ImageBuilder.Current.Build("~/temp/original.jpg", "~/uploads/cropped.jpg", settings);
```

Thanks

**Comment by lilith** [comment]
The `Instructions` class contains members [CropXUnits, CropYUnits, and CropRectangle](https://github.com/imazen/resizer/blob/develop/Core/Instructions.cs#L152-L161). 

ResizeSettings is deprecated in favor of Instructions.
