### ISSUE TITLE
Assemblies unsigned

### ISSUE THREAD

**Issue by jstemerdink** [imazen/resizer#157]
Could you please sign the assemblies, as in some projects resizer cannot be used because it is unsigned.

**Comment by lilith** [comment]
http://www.outercurve.org/blog/2014/03/25/Strongnaming-I-Do-Not-Think-It-Means-What-You-Thin/

In our context, strong naming would only cause harm and dependency hell. 

The software is OSS, and if you need signed assemblies for your build, you can create them with very little effort. However, we strongly advise against it, as it is an anti-pattern and provides a completely false sense of security.

**Comment by ImrePyhvel** [comment]
+1 to original request. 

Strong naming is not a security feature but one providing clear identity - which was developed exactly to combat the dll hell and ensure you only load things which are tested to work and redirect or load side-by-side in the rare case of transitive dependency conflict. But i do understand it is a religious issue.

Currently ImageResizer is a pain to maintain and keep up-to-date in strongly named projects. I urge the project maintainers reconsider where assembly identity management belongs to. Most OSS components provide both signed and unsigned these days to support both worlds.
