### ISSUE TITLE
Visiting .../resizer.debug.ashx causes a server error

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [imazen/resizer#158]
Hi there,

i added ImageResizer to an Orchard project and all is running fine and dandy but when i try to display the debug view by entering `../resizer.debug.ashx` in the browser i get the following error:

```
System.InvalidOperationException: Sequence contains no matching element

Stack Trace: 

[InvalidOperationException: Sequence contains no matching element]
   System.Linq.Enumerable.First(IEnumerable`1 source, Func`2 predicate) +2590046
   ImageResizer.Plugins.Basic.DiagnosticPageHandler.GenerateOutput(HttpContext context, Config c) +4772
   ImageResizer.Plugins.Basic.DiagnosticPageHandler.ProcessRequest(HttpContext context) +172
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +341
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69
```

I think you should call `FirstOrDefault()` instead of `First()` by a subsequent sanity check before accessing the affected enumerable.

So lonG

**Comment by lilith** [comment]
I believe this was fixed a few versions back? What are you currently using?

**Comment by ViRuSTriNiTy** [comment]
Hi, its the current version 4.0.0 available from nuget.

**Comment by lilith** [comment]
Can you reproduce this with 4.0.4?

**Comment by ViRuSTriNiTy** [comment]
Hi, nope 4.0.4 works great. Thanks for the update.
