### ISSUE TITLE
ImageResizer puts a red pixel on images?

### ISSUE THREAD

**Issue by Mds92** [imazen/resizer#159]
I was using ImageResizer 3.\* on my website.
Since I update it to `4.0.4` version, it puts a red dot on bottom right of each image.
What's wrong?

**Comment by lilith** [comment]
This means you are not licensed to use the product; visit the diagnostics page.

**Comment by vishnu4** [comment]
If we have paid for you to add functionality to imageresizer in the past (a couple of years ago), do we still have to purchase a license, or are we grandfathered into the basic package?

**Comment by lilith** [comment]
Hi Phil, including my Dec 6th response to you below:

---

Hi Phil,
I see a 6-month contract from Jan-July 2013, but that expired years before
ImageResizer v4 was released.  Free upgrades are only included for
customers with active support contracts. You would need to purchase a new
Elite license to receive the same products as before.

Best regards,
Nathanael Jones

**Comment by vishnu4** [comment]
Thanks, never got that e-mail, it must have been junked.  Will talk with my company about purchasing a license.
