### ISSUE TITLE
License key was issued in the future

### ISSUE THREAD

**Issue by aquamoth** [imazen/resizer#161]
I had my project owner buy a license for the performance bundle 30 minutes ago.
Installed the license to the config and tried it.

Only, I live in Sweden and he in Japan (and where your licensing server lives I have no idea...)  so I get this error when checking the license:

_resizer configuration(Warning):    License key was issued in the future; check system clock: cosmo-jpn.jp_

REALLY annoying! Please change to UTC time when issuing licenses, so the next poor sob doesn't have to wait a day to start using it.

**Comment by lilith** [comment]
Hi Mattias,

License keys are issued and verified in UTC time. The embedded time within
your license is 2016-01-20 11:31:41 UTC, which appears correct to me.  Have
you verified the UTC time on your server is correct?

**Comment by aquamoth** [comment]
Yes, the server – and my dev.machine both have correct time and TZ.

It started working after an hour or so (and I’m in utc+1) so I guess the verification isn’t done in utc after all?

Anyway, all works over here, so I’m good. Hope others arn’t having problems though.

/Mattias

**Comment by aquamoth** [comment]
Thanks for getting back to me.

I have a non-related issue, that I doubt is ImageResizers fault per se, but I’d really appreciate any input on.

Perhaps you have seen anything like this problem?

 http://stackoverflow.com/questions/34906351/azure-cdn-edge-in-japan-not-responsive http://stackoverflow.com/questions/34906351/azure-cdn-edge-in-japan-not-responsive

Yours,

/Mattias

**Comment by lilith** [comment]
We now add 24hrs grace period to avoid problematic clocks :)
