### ISSUE TITLE
PdfiumRenderer has a dependency on PdfiumViewer that documentation fails to mention

### ISSUE THREAD

**Issue by peaeater** [imazen/resizer#169]
The doc page for the PdfiumRenderer would have me believe that all I need is the latest pdfium.dll downloaded from https://github.com/pvginkel/PdfiumViewer/raw/master/Libraries/Pdfium/x86/pdfium.dll. Not true.

Even with the pdfium.dll in the right place (bin/x86/pdfium.dll), PdfiumRenderer 4.0.5 fails to render an image from a pdf with the following error:

> System.IO.FileNotFoundExceptionCould not load file or assembly 'PdfiumViewer, Version=2.7.0.0, Culture=neutral, PublicKeyToken=91e4789cfb0609e0' or one of its dependencies. The system cannot find the file specified.

If I download the 2.7.0 source code release from https://github.com/pvginkel/PdfiumViewer/releases, then compile the provided PdfiumViewer project and put it in the bin folder, that error goes away.

So, why is there a dependency on PdfiumViewer at all? And if there needs to be one, why does the doc page not mention it?

Furthermore, the bin/x86 and bin/x64 folders containing pdfium.dll need to have at least read+exec permissions for the relevant Application Pool Identity in an ASP.NET web application scenario, which again is not mentioned anywhere on the PdfiumRenderer documentation page.

**Comment by lilith** [comment]
If you use NuGet (which most people do), PdfiumViewer is automatically fetched:
https://github.com/imazen/resizer/blob/develop/nuget/ImageResizer.Plugins.PdfiumRenderer.nuspec

In which case the documentation should be correct. bin/\* typically defaults to read+exec permissions. I'd be interested in hearing how that configuration happened.

PdfiumViewer is in the /Contrib/ folder, and is community supported and documented - this would be the file to edit if you want to improve the state of documentation. It was created by the author of PdfiumViewer.
https://github.com/imazen/resizer/blob/develop/Contrib/PdfiumRenderer/readme.md

**Comment by peaeater** [comment]
Well, hm. I am using the Elite license DRM-free package source for NuGet, and I note the contents of the nuspec file that is fetched as part of the package is different than the link you give above, but it does list PdfiumViewer 2.7.0 as a dependency, so I must not be letting NuGet install the dependencies properly. 

On the bin/\* front, though, read+exec is only the default if one sets up one's IIS website with Network Service as the application pool identity. However, it is more and more common these days to use the application pool's Application Pool Identity, which is a kind of dynamic credential that does not have default permissions set anywhere (unlike Network Service which already has read+exec all over the place). So, I specify Application Pool Identity and set permissions on my website files to the least needed, which to date has always been read-only on bin/*. Not a problem bumping it up to read+exec, and in hindsight it seems obvious, but it would be nice if the documentation was explicit about it. 

I'll have a go at updating the PdfiumRender readme.md page with tips on permissions and the PdfiumViewer dependency for those who haven't necessarily gone the NuGet route. 

Thanks for your reply.

**Comment by tiesont** [comment]
@nathanaeljones I've actually found that [PDFiumSharp](https://github.com/ArgusMagnus/PDFiumSharp) seems faster and has a somewhat simpler API. If I were to do the work of porting PdfiumRenderer to use that project, would the pull-request be reviewed anytime soon?

**Comment by lilith** [comment]
Yes!

**Comment by lilith** [comment]
Yes!

**Comment by tiesont** [comment]
Cool beans.

The PDFiumSharp library seems to be targeting .NET Standard / .NET Core (my experience in the "new" .NET is fairly limited, so I'm not sure on which it is). I had to make a few changes to make it work with .NET Framework (targeting 4.6) - do you have a preference for which framework the PdfiumRenderer plugin should target? Would it make the most sense to create a new plugin called PdfiumRenderer2, similar to AzureReader2, S3Reader2, etc.?

**Comment by lilith** [comment]
Yes, PdfiumRenderer2 sounds good. IR 5 will target .NET Standard 2.0

**Comment by tiesont** [comment]
Okay. Does it make sense to create a new issue for this, or is replacing the PdfiumViewer dependency on-topic for this issue?

I am using PDFiumSharp in a .NET 4.6 project, which is where I'd need PdfiumRenderer2, so I'll have to take a stab at enabling multi-framework support, unless you want it to only target .NET Standard 2.0 (which I haven't worked with at all, to be honest). Also, is there a different plugin template for IR 5? If not, I would assume I'd just start with the current plugin and make whatever changes are required.

**Comment by lilith** [comment]
A new issue would be preferable. There will be plugin changes in IR 5, but
I'll help with that migration.

On Oct 2, 2017 3:12 PM, "Tieson Trowbridge" <notifications@github.com>
wrote:

Okay. Does it make sense to create a new issue for this, or is replacing
the PdfiumViewer dependency on-topic for this issue?

I am using PDFiumSharp in a .NET 4.6 project, which is where I'd need
PdfiumRenderer2, so I'll have to take a stab at enabling multi-framework
support, unless you want it to only target .NET Standard 2.0 (which I
haven't worked with at all, to be honest). Also, is there a different
plugin template for IR 5? If not, I would assume I'd just start with the
current plugin and make whatever changes are required.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/imazen/resizer/issues/169#issuecomment-333666657>, or mute
the thread
