### ISSUE TITLE
Exception in httpModule

### ISSUE THREAD

**Issue by odrix** [imazen/resizer#173]
Hello,

I use ImageResizer in HttpModule mode, and I encountred this exception : ArgumentException 

```
Exception message: Source may only be an instance of string, VirtualFile, IVirtualBitmapFile, HttpPostedFile, HttpPostedFileBase, Bitmap, Image, or Stream.
Nom du paramètre : source
   à ImageResizer.ImageBuilder.LoadImage(Object source, ResizeSettings settings, Boolean restoreStreamPos)
   à ImageResizer.ImageBuilder.BuildJob(ImageJob job)
   à ImageResizer.ImageBuilder.Build(ImageJob job)
   à ImageResizer.ImageBuilder.Build(Object source, Object dest, ResizeSettings settings, Boolean disposeSource, Boolean addFileExtension)
   à ImageResizer.ImageBuilder.Build(Object source, Object dest, ResizeSettings settings, Boolean disposeSource)
   à ImageResizer.ImageBuilder.Build(Object source, Object dest, ResizeSettings settings)
   à ImageResizer.InterceptModule.<>c__DisplayClass5_0.<HandleRequest>b__1(Stream stream)
   à ImageResizer.Plugins.Basic.NoCacheHandler.ProcessRequest(HttpContext context)
   à System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   à System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

Can you catch this Exception in your custom HttpModule
Or how can I catch it to not see it in my Event Log ?

Thanks for your answer.

**Comment by lilith** [comment]
This is remarkable; I've never seen this before. Can you reproduce it on demand?

**Comment by odrix** [comment]
not on demand, but it happens frequently.

to complete I use an IVirtualImageProvider and IVirtualFile to provide a stream from a cloud storage and sometime this cloud close the connection before the stream end readed… so the exception appear

**Comment by lilith** [comment]
I would need to see the code you're using.

**Comment by lilith** [comment]
Have you set up an integration test to simulate network failure? This should help you troubleshoot. Can you set a conditional breakpoint to verify that your provider never returns (null) from `.Open()`?

Will re-open if I get a response.
