### ISSUE TITLE
Remote URL with square brackets does not work

### ISSUE THREAD

**Issue by marcselman** [imazen/resizer#174]
I have the following image:
http://www.dressboys.nl/upload/18/products/130/design-dressboy---aluminium---lilianshouse[0].jpg

If I try to use the RemoteReader plugin with that URL it won't work.
I've tried various encoded formats:

`~/remote/www.dressboys.nl%2fupload%2f18%2fproducts%2f130%2fdesign-dressboy---aluminium---lilianshouse[0].jpg`
`~/remote/www.dressboys.nl%2fupload%2f18%2fproducts%2f130%2fdesign-dressboy---aluminium---lilianshouse%5B0%5D.jpg`
`~/remote/www.dressboys.nl%2fupload%2f18%2fproducts%2f130%2fdesign-dressboy---aluminium---lilianshouse%255B0%255D.jpg`

**Comment by lilith** [comment]
This would be in the ASP.NET/IIS side. You may need to use the base64 format for these URLs.

**Comment by marcselman** [comment]
Well I've tested all that and looked at the ImageResizer sourcecode. I'm sure it should be fixed in ImageResizer. Have you at least tested it before closing the issue?

**Comment by lilith** [comment]
You tried using CreateSignedUrl ? None of the examples are using that format. Happy to re-open if we can isolate to ImageResizer, or (better yet) create a failing test case.
