### ISSUE TITLE
[Q] Why does it fast ?

### ISSUE THREAD

**Issue by nvcken** [imazen/resizer#175]
Can anyone explain why does it fast / low latency ?
I saw it rely on OpenCV so that is the reason make it fast ?

**Comment by lilith** [comment]
ImageResizer v4 has a custom rendering engine which outperforms all competing libraries that are capable of similar quality. 

http://imageresizing.net/docs/v4/plugins/fastscaling

We only use OpenCV for face detection. 

TLDR; High-quality image scaling is usually very slow, but our optimized C algorithms work very efficiently with modern CPUs and are cache-friendly.
