### ISSUE TITLE
ImageResizer adding gAMA and sRGB in png

### ISSUE THREAD

**Issue by domain-sli** [imazen/resizer#181]
We are using ImageResizer to resize the image on server side. But with some png image it will insert some meta data called gAMA and sRGB, it will cause color issue in output image. Is there a way to get rid of that?

![](http://i.stack.imgur.com/FtHKn.png)

**Comment by lilith** [comment]
sRGB: Perceptual and gAMA 0.45455 are the appropriate default values for those parameters, and should improve the consistency of rendering. Typically, their presence (at those values) is a good thing. Can you explain the 'color issue'?

That said, it's strange that you're seeing so much metadata - ImageResizer doesn't copy that by default. Unless you are using the CopyMetadata plugin, I don't think ImageResizer encoded this.

Can you please post the original file, the diagnostics page, and the output file you're seeing?
