### ISSUE TITLE
Obsolete Documentation

### ISSUE THREAD

**Issue by jamierytlewski** [imazen/resizer#187]
I was going to update the documentation, but I was just wondering if it was worth the time with some of the functions being obsolete. 

I noticed when I updated it said that `ResizeSettings` was obsolete and to use `Instructions` instead. I believe the docs should be updated to show this, but I wanted to know if I do will it be accepted.

Thanks!

**Comment by lilith** [comment]
Hi Jamie, absolutely! Our docs are in poor shape, and we're stretched very
thin  right now. Each plugin in this repo has a markdown file that gets
dumped into imazen/resizer-web via a git tool. Doc changes on the master/v4
branch and v3 branch end up on ImageResizing.net/docs/v3 and v4

If there is anything I can do to facilitate, let me know!
