### ISSUE TITLE
ImageResizer.Plugins.WebP issues: Unable to load DLL 'libwebp' / Unable to find an entry point named 'WebPSafeFree' in DLL 'libwebp'.

### ISSUE THREAD

**Issue by antonkallenberg** [imazen/resizer#191]
.NET Version: 4.6.1
ASP.NET Web API Version: 5.2.3
ImageResizer version: 4.0.5
ImageResizer.Plugins.WebP version: 4.0.5
ImageResizer.Plugins.AzureReader2 version: 4.0.5
ImageResizer.WebConfigAsync version: 4.0.5
Imazen.WebP version: 9.0.1
ImageResizer License: Free (We'll get the Elite license if WebP works)
## Steps to reproduce (Step by step from the [documentation](https://imageresizing.net/docs/v4/plugins/webp))
1. Install the package through the Package Manager Console (Install-Package ImageResizer.Plugins.WebP)
2. Add WebPEncoder and WebPDecoder to the plugin section in web.config: 

``` xml
<plugins>
  <add name="WebPEncoder" />
  <add name="WebPDecoder" />
</plugins>
```
## Result

![image](https://cloud.githubusercontent.com/assets/818051/18548076/283e350a-7b47-11e6-84d3-a3a284e888f9.png)
## Non working work around (Not mentioned in the documentation, but found in a comment)
1. Add **downloadnativedependencies="true"** to the plugins nodes in web.config:

``` xml
<plugins>
  <add name="WebPEncoder" downloadnativedependencies="true" />
  <add name="WebPDecoder" downloadnativedependencies="true" />
</plugins>
```
## Result

![image](https://cloud.githubusercontent.com/assets/818051/18548662/3dd0f7ce-7b4a-11e6-957b-61ff62631df6.png)

Is this a known issue or am I missing something?

**Comment by ruant** [comment]
I've got Imazen.WebP version 10.0.1 installed.
Still not working.

Any news?

**Comment by lilith** [comment]
I think our last update worked. The issues went away with libwebp 0.6 for some reason.

**Comment by ruant** [comment]
@nathanaeljones Thanks for the reply. I'll give this another try.

**Comment by MrChriZ** [comment]
Not working here :s

**Comment by lilith** [comment]
What versions of dlls are you using?

**Comment by MrChriZ** [comment]
Via Nuget I installed Imazen.WebP version 10.0.1
and ImageResizer.Plugins.WebP  version 4.1.9

This was working previously.... but even uninstalling and reinstalling those packages isn't working at the moment.

**Comment by lilith** [comment]
This problem is caused by having an outdated libwebp.dll

**Comment by MrChriZ** [comment]
dumb question but how do I update it?
Thanks.

**Comment by lilith** [comment]
Copy paste a new one into /bin

**Comment by MrChriZ** [comment]
Thanks Nathan.
