### ISSUE TITLE
Image is not processed if Url contains commas (",")

### ISSUE THREAD

**Issue by valdisiljuconoks** [imazen/resizer#195]
Hi,

Because of the framework we are relying on, in particular cases Url for the image gets generated something like this:

```
http://localhost/batman.jpg,,164?....&w=100&h=150
```

Seems like IR is skipping these kind of urls. If I'm removing ",,164" - image gets resized and works as expected.

Any ideas? Thanks!

**Comment by lilith** [comment]
Commas are part of the path name. ImageResizer is acting correctly in ignoring URLs that don't end in an image extension.

**Comment by valdisiljuconoks** [comment]
Ok, then this is by design and we need to find another way around. Thanks!
