### ISSUE TITLE
Clean & Customized Filename

### ISSUE THREAD

**Issue by KiarashS** [imazen/resizer#198]
Dear,

How we can replace `whitespaces` with `dash symbol (-)` in the filename when we use `<filename>` variable with `ImageJob`?

For example:
`Beautiful Red Flower-a86f55afda334ece9e7eafea46ab646d.jpg` => `Beautiful-Red-Flower-a86f55afda334ece9e7eafea46ab646d.jpg.jpg`

**Comment by lilith** [comment]
I suggest using String.Replace or a Regex and then providing ImageJob the filename. If you want to keep the extension, you can use `.<ext>` to have it expanded. 

The implementation we use is https://github.com/imazen/resizer/blob/e7d2a5a47b9301c4c3b3b863716946c4b58b5ec7/Core/ImageJob.cs#L308 and https://github.com/imazen/resizer/blob/e7d2a5a47b9301c4c3b3b863716946c4b58b5ec7/Core/Util/PathUtils.cs#L534

Our implementation only supports stripping non-whitelisted characters; it doesn't support replacing them.

**Comment by KiarashS** [comment]
So, In this case how i can change file name in HttpPostedFileBase? (for example, `.Replace(" ", "-")`)

```
ImageJob i = new ImageJob(image,
                          uploadFolder + "<filename>-<guid>.<ext>",
                          settings);

```

type of `image` is `HttpPostedFileBase`.
