### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by eman1986** [imazen/resizer#201]
Do you have any plans to support .NET Core?

I'm going to be switching to it for new projects so was hoping to see support for it.

**Comment by lilith** [comment]
Yes. To do that, I'm [creating](https://github.com/imazen/imageflow/graphs/contributors) Imageflow, a cross-platform image processing library that can work under .NET Core and is suitable for server-side use. ImageResizer currently uses many Windows APIs, which prevent it from supporting .NET Core. 

Related: [C# Bindings for Imageflow](https://github.com/imazen/imageflow/issues/67)

Previous thread on this topic: https://github.com/imazen/resizer/issues/116

**Comment by lilith** [comment]
This is complete in https://github.com/imazen/imageflow-dotnet-server
