### ISSUE TITLE
How to optimize images using resizer

### ISSUE THREAD

**Issue by amitt0488** [imazen/resizer#204]
Can we optimize the image using imageresizing.net ?

If yes, then how to do it.

**Comment by lilith** [comment]
One of the most important ways to optimize images is to avoid sending unneeded pixels to browsers; ImageResizer's HTTP API makes this much easier and more practical. 

Determining an effective jpeg quality setting is also important. If your client has a high-density display, and you are sending enough pixels for each hardware pixel, you can usually afford to turn the quality down a bit - from 90 (the default) to 85 or 80. 

ImageResizer focuses on speed and visual quality over file size. Using offline tools that can afford to spend many seconds of computation per image (or minutes, like guetzli), will net you additional size reductions. This, of course, means a more complicated and slower workflow for your images, so you'll want to consider the implications.

 Imageflow will be able to do more advanced optimizations on file size, and will have a 'slow' mode that allows for long processing times per image.
