### ISSUE TITLE
Will there be official support for guetzli?

### ISSUE THREAD

**Issue by ruant** [imazen/resizer#206]
So Google have managed to shrink the jpg files by 20-30%.  
https://github.com/google/guetzli/
Will this be available in imageresizer3/4?
Maybe as a plugin if that's easiest?

**Comment by lilith** [comment]
They're looking at 1 minute per megapixel on a desktop machine. At ten minutes per smartphone image, would this be feasible for you?

**Comment by ruant** [comment]
Wow, didn't read that part.
Just saw 20-30% smaller file sizes and thought that was awesome.

It's probably useful for offline compressing but on-the-fly that won't work.

Thanks for getting back to me tho.
Keep up the good work 👍

**Comment by jcupitt** [comment]
Their encoder can also need many GB of memory for a large image, and it's just a command-line utility, you can't call it as a library. Maybe in a few years they'll improve it enough to be practical.

[mozjpeg](https://github.com/mozilla/mozjpeg) is Mozilla's improved encoder. They started with the standard libjpeg and added a range of extra features, like trellis quantization, which together can give a ~35% size reduction. It runs in a modest amount of memory, it's fast, and it has an API that's a simple extension of an existing one. It might be a better project to look at.
