### ISSUE TITLE
Removing SizeLimiting Plugin does not work

### ISSUE THREAD

**Issue by chrjsorg** [imazen/resizer#207]
I'm using ImageResizer to convert uploaded images and save them to a Azure Cloud Blob Storage.

It is not very common, but I need to upload files bigger than 4mb, thats why I wanted to disable the SizeLimiting Plugin. Which is documented here.

Unfortunately after I removed the plugin I still can't upload larger files.

```{"File may be corrupted, empty, or may contain a PNG image with a single dimension greater than 65,535 pixels."}```

Within the diagnostics page the SizeLimiting plugin can not be found so I assume its disabled.

Any advice?

Example Image:
https://drive.google.com/file/d/0B-6vgZ0ErQZuVUpjMlN4SHVKTlU/view?usp=sharing

**Comment by lilith** [comment]
I uploaded this to the test server and it works fine: http://z.zr.io/ri/private/we3.png?width=600

I think something is corrupting the data stream. SizeLimiting doesn't limit by megabytes, but rather by output dimensions. So if ?width=300 doesn't work, it's not SizeLimiting related.

**Comment by lilith** [comment]
Will reopen with code sample.
