### ISSUE TITLE
Does Resizer support .ico file extension?

### ISSUE THREAD

**Issue by huulocnguyen** [imazen/resizer#208]
Dear,
I saw below information in ./resizer.debug.ashx page.
Accepted file extensions: bmp, gif, exif, png, tif, tiff, tff, jpg, jpeg, jpe, jif, jfif, jfi, 

Could I ask Resizer can support .ico file extension and how I can configure that?

**Comment by lilith** [comment]
ImageResizer does not produce .ico files. 

What problem are you trying to solve/what are you trying to do?

**Comment by huulocnguyen** [comment]
Dear Nathanaeljones,
Now I managed a list of images included .ico, png, jpg on Blob azure. I show the images to my clients via new my domain point to hosting using ImageResizer. But I could not show .ico file. I have to use the original domain of blob azure to show .ico files and using new domain to show other file types. It's not convenient when using two domains. 
Could I ask ImageResizer will soon  support .ico file in future?

**Comment by lilith** [comment]
I'm sorry, we don't have plans to do this. .ico files aren't within our design scope.
