### ISSUE TITLE
sRotate doesn't work with manual cropping

### ISSUE THREAD

**Issue by tranan89** [imazen/resizer#210]
Hi,

It seems like manual cropping is ignored when sRotate is supplied.
See below example

Supplied query: srotate=90&crop=687,615,2653,3102

Expected outcome
![expected outcome](https://cloud.githubusercontent.com/assets/8797144/24356012/89a6dc5e-12f8-11e7-8300-9a2496242c5d.PNG)

Actual outcome
![actual outcome](https://cloud.githubusercontent.com/assets/8797144/24356008/84b3ac54-12f8-11e7-97bd-7e0694dde509.jpg)

Original
![pt](https://cloud.githubusercontent.com/assets/8797144/24356115/ed3bd116-12f8-11e7-8e15-6f5ed6675740.jpg)

I'm using version 3.3.1.526

Regards
Peter

**Comment by lilith** [comment]
The crop coordinates need to be relative to the rotated copy of the image. We don't support 3.3 anymore, but does `?srotate=90&crop=10,10,80,80&cropxunits=100&cropyunits=100` work?

**Comment by tranan89** [comment]
Thanks for the fast response.

The code snippet didnt work (same result). However upgrading to 3.4.3.103 solved the issue! :)
I should have updated the version to begin with, sorry for wasting your time.
