### ISSUE TITLE
Png file size increases when resizing

### ISSUE THREAD

**Issue by johansuperstar** [imazen/resizer#212]
Hi!

I have a .png file that is 52 KB and when I resize it through ImageResizer to be 1px less in width, the file size increases to 263 KB.

I'm using ImageResizer version 4.0.4.

What can be the cause of this?

Regards
Johan

**Comment by lilith** [comment]
Can you share the image? It's quite strange that a 1px image would be that large.

**Comment by johansuperstar** [comment]
It's not 1px, I'm resizing it 1px in width from 569px to 568px. I first noticed the issue when it was resized to 480px and discovered that it kept growing as I increased the width up until 569px.
Here's the picture http://www.littlefarmer.se/siteassets/products/teasers/teaser-mild-naturell-havregrot-6-manader.png

**Comment by lilith** [comment]
Ah. You're starting with a heavily optimized 8-bit PNG. 

ImageResizer defaults to 32-bit PNG images. You may be able to use `colors=255` and PrettyGifs to reduce that size a bit, but ImageResizer really can't compete with offline tools (yet). We're using the Windows API for PNG encoding. We'll be changing that with Imageflow.

**Comment by johansuperstar** [comment]
Alright! Thanks for your answer, I'll keep my eyes open of Imageflow then :)
