### ISSUE TITLE
RemoteReader Exception thrown for browser-supported URLs that are non-spec

### ISSUE THREAD

**Issue by edmacdonald** [imazen/resizer#220]
The use of Uri.IsWellFormedUriString is causing an exception for Urls that may technically be invalid based on the RFC but are in use and supported by most, if not all, browsers.  Here is an example from Volvo's site:

`https://www.volvopartshop.com/ekmps/shops/tmsvolvo/images/v50-roof-rail-end-caps-black--front-or-rear-front-side-right-hand-18052-p[ekm]299x224[ekm].jpg`

We are using ImageResizer in an environment where we don't have control over source image URLs.

I submitted a PR for a configuration option to skip this check, but for some reason (not code related) the build is failing.

-Ed

**Comment by lilith** [comment]
Fixed with https://github.com/imazen/resizer/pull/221
