### ISSUE TITLE
 ImageResizer in Asp.net WebApi project  always restart Application

### ISSUE THREAD

**Issue by jrt324** [imazen/resizer#226]
I have tried using ImageResizer  in my test Asp.net WebApi project, but when i follows the steps:
```
PM> Install-Package ImageResizer.MvcWebConfig
PM> Install-Package ImageResizer.Plugins.DiskCache
PM> Install-Package ImageResizer.Plugins.PrettyGifs

```
F5 Run the project , every time refresh the page, it always call the void Application_Start method, 
if i remove the <section name="resizer" type="ImageResizer.ResizerSection" in web.config,  WebApi project work fine.

Please tell What's happened?

**Comment by lilith** [comment]
Can you share the diagnostics page /resizer.debug?

**Comment by jrt324** [comment]
Diagnostics for ImageResizer 4.1.9 008a626e at localhost generated 2017/9/20 1:47:37
Please remember to provide this page when contacting support.


You are using ImageResizer Essential Edition plugins.

3 issues detected:

Plugins(ConfigurationError):	An instance of the specified plugin (ImageResizer.Plugins.Basic.ClientCache) has already been added. Implement IMultiInstancePlugin if the plugin supports multiple instances.
			

(Warning):	To potentially see additional errors here, perform an image resize request.
			

(Warning):	NoCache is only for development usage, and cannot scale to production use.
			Add DiskCache or CloudFront for production use




Configuration:

<resizer>
<pipeline fakeExtensions=".ashx" defaultCommands="autorotate.default=true" />
<plugins>
<add name="VirtualFolder" virtualPath="~/" physicalPath=".\Images" />
<add name="ClientCache" />
</plugins>
</resizer>


Registered plugins:

ImageResizer.Plugins.Basic.DefaultEncoder
ImageResizer.Plugins.Basic.NoCache
ImageResizer.Plugins.Basic.ClientCache
ImageResizer.Plugins.Basic.WebConfigLicenseReader
ImageResizer.Plugins.Basic.Diagnostic
ImageResizer.Plugins.Basic.SizeLimiting
ImageResizer.Plugins.Basic.MvcRoutingShimPlugin
ImageResizer.Plugins.Basic.LicenseDisplay
ImageResizer.Plugins.Basic.VirtualFolder

Accepted querystring keys:

quality, format, thumbnail, maxwidth, maxheight, width, height, w, h, crop, page, bgcolor, rotate, flip, sourceFlip, sFlip, sRotate, borderWidth, borderColor, paddingWidth, paddingColor, frame, useresizingpipeline, cache, process, margin, dpi, zoom, autorotate

Accepted file extensions:

bmp, gif, exif, png, tif, tiff, tff, jpg, jpeg, jpe, jif, jfif, jfi

Environment information:

Running Microsoft-IIS/10.0 on Microsoft Windows NT 10.0.14393.0 and CLR 4.0.30319.42000
Trust level: Unrestricted
OS bitness: x86 !! Warning, running as 32-bit on a 64-bit OS(AMD64). This will limit ram usage !!
Executing assembly: C:\Program Files (x86)\IIS Express\iisexpress.exe
IntegratedPipeline: True

Installed HttpModules: 

System.Web.Caching.OutputCacheModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key OutputCache)
System.Web.SessionState.SessionStateModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key Session)
System.Web.Security.WindowsAuthenticationModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key WindowsAuthentication)
System.Web.Security.FormsAuthenticationModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key FormsAuthentication)
System.Web.Security.DefaultAuthenticationModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key DefaultAuthentication)
System.Web.Security.RoleManagerModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key RoleManager)
System.Web.Security.UrlAuthorizationModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key UrlAuthorization)
System.Web.Security.FileAuthorizationModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key FileAuthorization)
System.Web.Security.AnonymousIdentificationModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key AnonymousIdentification)
System.Web.Profile.ProfileModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key Profile)
System.Web.UrlMappingsModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key UrlMappingsModule)
System.ServiceModel.Activation.ServiceHttpModule, System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35          (under key ServiceModel-4.0)
System.Web.Routing.UrlRoutingModule, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key UrlRoutingModule-4.0)
System.Web.Handlers.ScriptModule, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35          (under key ScriptModule-4.0)
ImageResizer.InterceptModule, ImageResizer, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null          (under key ImageResizingModule)
Microsoft.VisualStudio.Web.PageInspector.Runtime.Tracing.PageInspectorHttpModule, Microsoft.VisualStudio.Web.PageInspector.Runtime, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a          (under key __DynamicModule_Microsoft.VisualStudio.Web.PageInspector.Runtime.Tracing.PageInspectorHttpModule, Microsoft.VisualStudio.Web.PageInspector.Runtime, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a_9f2d07fe-247d-4142-90ee-0d794621956c)
System.Web.WebPages.WebPageHttpModule, System.Web.WebPages, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35          (under key __DynamicModule_System.Web.WebPages.WebPageHttpModule, System.Web.WebPages, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35_650fc62b-dae3-4152-9d20-2854cc548a3d)

Loaded assemblies:

mscorlib                                 File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
System.Web                               File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
System                                   File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
System.Core                              File: 4.6.1638.0 (4.0.0.0)      Informational: 4.6.1638.0                     
System.Configuration                     File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.Xml                               File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.Web.ApplicationServices           File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
System.Runtime.Caching                   File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
Microsoft.Build.Utilities.v4.0           File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.Web.RegularExpressions            File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
Microsoft.JScript                        File: 14.6.1586.0 (10.0.0.0)    Informational: 14.6.1586.0                    
System.Web.WebPages.Deployment           File: 3.0.30128.0 (3.0.0.0)     Informational: 3.0.3-30128 (0e974218e12a67d4b1f25422119e40cfe6953e46)  
System.Web.Mvc                           File: 5.2.30128.0 (5.2.3.0)     Informational: 5.2.3-30128 (0e974218e12a67d4b1f25422119e40cfe6953e46)  
System.Web.WebPages                      File: 3.0.30128.0 (3.0.0.0)     Informational: 3.0.3-30128 (0e974218e12a67d4b1f25422119e40cfe6953e46)  
Microsoft.VisualStudio.Web.PageInspector.Loader File: 15.0.30726.0 (1.0.0.0)    Informational: 15.0.30726.0.Release.b533      
System.Web.WebPages.Razor                File: 3.0.30128.0 (3.0.0.0)     Informational: 3.0.3-30128 (0e974218e12a67d4b1f25422119e40cfe6953e46)  
System.Web.WebPages.Deployment           File: 2.0.20710.0 (2.0.0.0)     Informational:                                
Microsoft.VisualStudio.Web.PageInspector.Runtime File: 15.0.30726.0 (15.0.0.0)   Informational: 15.0.30726.0.Release.b533      
Microsoft.Web.Infrastructure             File: 1.0.20105.407 (1.0.0.0)   Informational:                                
App_global.asax.gkjijs1b                 File:  (0.0.0.0)                Informational:                                
FileServer                               File: 1.0.0.0 (1.0.0.0)         Informational:                                
System.ServiceModel.Activation           File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.ServiceModel.Internals            File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
System.ServiceModel                      File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
SMDiagnostics                            File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
System.Web.Extensions                    File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
Microsoft.CSharp                         File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.Data                              File: 4.6.1636.0 (4.0.0.0)      Informational: 4.6.1636.0                     
System.Web.Services                      File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.Drawing                           File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.EnterpriseServices                File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.IdentityModel                     File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
System.Runtime.Serialization             File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
System.ServiceModel.Web                  File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.Activities                        File: 4.6.1637.0 (4.0.0.0)      Informational: 4.6.1637.0                     
System.ServiceModel.Activities           File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.WorkflowServices                  File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.Data.DataSetExtensions            File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.Xml.Linq                          File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.ComponentModel.DataAnnotations    File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
System.Web.DynamicData                   File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
ImageResizer                             File: 4.1.9.1086 (4.0.0.0)      Informational: 4.1.9 008a626e                 
Newtonsoft.Json                          File: 6.0.4.17603 (6.0.0.0)     Informational:                                
System.Net.Http.Formatting               File: 5.2.30128.0 (5.2.3.0)     Informational: 5.2.3-30128 (0e974218e12a67d4b1f25422119e40cfe6953e46)  
System.Web.Helpers                       File: 3.0.30128.0 (3.0.0.0)     Informational: 3.0.3-30128 (0e974218e12a67d4b1f25422119e40cfe6953e46)  
System.Web.Http                          File: 5.2.30128.0 (5.2.3.0)     Informational: 5.2.3-30128 (0e974218e12a67d4b1f25422119e40cfe6953e46)  
System.Web.Http.WebHost                  File: 5.2.30128.0 (5.2.3.0)     Informational: 5.2.3-30128 (0e974218e12a67d4b1f25422119e40cfe6953e46)  
System.Web.Razor                         File: 3.0.30128.0 (3.0.0.0)     Informational: 3.0.3-30128 (0e974218e12a67d4b1f25422119e40cfe6953e46)  
Microsoft.VisualStudio.Web.PageInspector.Tracing File: 15.0.30726.0 (15.0.0.0)   Informational: 15.0.30726.0.Release.b533      
System.Net.Http                          File: 4.6.1586.0 (4.0.0.0)      Informational: 4.6.1586.0                     
mscorlib.resources                       File:  (4.0.0.0)                Informational:                                



When fetching a remote license file (if you have one), the following information is sent via the querystring.
                         license_id [integer]
                         manager_id [guid]
                   total_heartbeats [integer]
                     new_heartbeats [integer]
                    first_heartbeat [integer]
                  reporting_version 3
                            proc_64 0
                          proc_guid cSpl77MgnUSRPsfTWQLXRQ
                    proc_sys_dotnet 4.6.2
                           proc_iis 10.0
           proc_integrated_pipeline 1
                   proc_asyncmodule 0
              proc_default_commands autorotate.default=true
                proc_working_set_mb 79
                    proc_git_commit 008a626e
                  proc_info_version 4.1.9
                  proc_file_version 4.1.9.1086
                  proc_apppath_hash pyjFj2Z6
                                mod .Caching.OutputCacheModule
                                mod .SessionState.SessionStateModule
                                mod .WindowsAuthenticationModule
                                mod .FormsAuthenticationModule
                                mod .DefaultAuthenticationModule
                                mod .RoleManagerModule
                                mod .UrlAuthorizationModule
                                mod .FileAuthorizationModule
                                mod .AnonymousIdentificationModule
                                mod .Profile.ProfileModule
                                mod .UrlMappingsModule
                                mod System.ServiceModel.Activation.ServiceHttpModule
                                mod .Routing.UrlRoutingModule
                                mod .Handlers.ScriptModule
                                mod ImageResizer.InterceptModule
                                mod Microsoft.VisualStudio.Web.PageInspector.Runtime.Tracing.PageInspectorHttpModule
                                mod .WebPages.WebPageHttpModule
                    h_logical_cores 4
                       h_mac_digest cMher9uZGars_XkvSKcVrQ
                             h_os64 1
             h_network_drives_count 0
               h_other_drives_count 0
               h_fixed_drives_count 7
                      h_fixed_drive NTFS,1,85
                      h_fixed_drive NTFS,5,34
                      h_fixed_drive NTFS,15,322
                      h_fixed_drive NTFS,3767,4000
                      h_fixed_drive NTFS,29,1500
                      h_fixed_drive NTFS,21,339
                      h_fixed_drive NTFS,46,338
                                  p SizeLimiting
                                  p VirtualFolder
              counter_update_failed 0
               encoded_pixels_total 0
      encoded_pixels_per_second_max 0
      encoded_pixels_per_minute_max 0
     encoded_pixels_per_15_mins_max 0
        encoded_pixels_per_hour_max 0
               jobs_completed_total 0
      jobs_completed_per_second_max 0
      jobs_completed_per_minute_max 0
     jobs_completed_per_15_mins_max 0
        jobs_completed_per_hour_max 0
               decoded_pixels_total 0
      decoded_pixels_per_second_max 0
      decoded_pixels_per_minute_max 0
     decoded_pixels_per_15_mins_max 0
        decoded_pixels_per_hour_max 0
                   blob_reads_total 0
          blob_reads_per_second_max 0
          blob_reads_per_minute_max 0
         blob_reads_per_15_mins_max 0
            blob_reads_per_hour_max 0
              blob_read_bytes_total 0
     blob_read_bytes_per_second_max 0
     blob_read_bytes_per_minute_max 0
    blob_read_bytes_per_15_mins_max 0
       blob_read_bytes_per_hour_max 0
                   source_width_5th 0
                  source_width_25th 0
                  source_width_50th 0
                  source_width_75th 0
                  source_width_95th 0
                 source_width_100th 0
                  scaling_ratio_5th 0
                 scaling_ratio_25th 0
                 scaling_ratio_50th 0
                 scaling_ratio_75th 0
                 scaling_ratio_95th 0
                scaling_ratio_100th 0
                   encode_times_5th 0
                  encode_times_25th 0
                  encode_times_50th 0
                  encode_times_75th 0
                  encode_times_95th 0
                 encode_times_100th 0
                   output_width_5th 0
                  output_width_25th 0
                  output_width_50th 0
                  output_width_75th 0
                  output_width_95th 0
                 output_width_100th 0
            output_aspect_ratio_5th 0
           output_aspect_ratio_25th 0
           output_aspect_ratio_50th 0
           output_aspect_ratio_75th 0
           output_aspect_ratio_95th 0
          output_aspect_ratio_100th 0
                   decode_times_5th 0
                  decode_times_25th 0
                  decode_times_50th 0
                  decode_times_75th 0
                  decode_times_95th 0
                 decode_times_100th 0
                blob_read_times_5th 0
               blob_read_times_25th 0
               blob_read_times_50th 0
               blob_read_times_75th 0
               blob_read_times_95th 0
              blob_read_times_100th 0
             collect_info_times_5th 0
            collect_info_times_25th 0
            collect_info_times_50th 0
            collect_info_times_75th 0
            collect_info_times_95th 0
           collect_info_times_100th 0
                  source_height_5th 0
                 source_height_25th 0
                 source_height_50th 0
                 source_height_75th 0
                 source_height_95th 0
                source_height_100th 0
                      job_times_5th 0
                     job_times_25th 0
                     job_times_50th 0
                     job_times_75th 0
                     job_times_95th 0
                    job_times_100th 0
                  source_pixels_5th 0
                 source_pixels_25th 0
                 source_pixels_50th 0
                 source_pixels_75th 0
                 source_pixels_95th 0
                source_pixels_100th 0
                  output_height_5th 0
                 output_height_25th 0
                 output_height_50th 0
                 output_height_75th 0
                 output_height_95th 0
                output_height_100th 0
            source_aspect_ratio_5th 0
           source_aspect_ratio_25th 0
           source_aspect_ratio_50th 0
           source_aspect_ratio_75th 0
           source_aspect_ratio_95th 0
          source_aspect_ratio_100th 0
                 job_other_time_5th 0
                job_other_time_25th 0
                job_other_time_50th 0
                job_other_time_75th 0
                job_other_time_95th 0
               job_other_time_100th 0
                  output_pixels_5th 0
                 output_pixels_25th 0
                 output_pixels_50th 0
                 output_pixels_75th 0
                 output_pixels_95th 0
                output_pixels_100th 0
                      image_domains 
                       page_domains 
                         query_keys 
               extra_job_query_keys

**Comment by lilith** [comment]
Strange. Could you zip that project up and attach it? You can also email it to support@imageresizing.net
