### ISSUE TITLE
Dynamic Installation of Plugin modifying RouteCollection

### ISSUE THREAD

**Issue by bwaldron** [imazen/resizer#228]
We are seeing an issue where the MVC RouteCollection is being modified and isolated it down to this code.

var config = new ImageResizer.Configuration.Config();
var instructions = new Instructions(querystring);
new WhitespaceTrimmerPlugin().Install(config);
var job = new ImageJob(stream, ms, instructions);

It is possible that by dynamically installing a plugin, in this case WhitespaceTrimmer, that the MVC Shim is getting executed and modifying the RouteTable?  If so, is there a way to disable?

The error is exactly as described in this SO article:  https://stackoverflow.com/questions/1899188/exceptions-in-system-web-routing-routecollection-getroutedata

If it matters, we are Kickstarter supporters.

**Comment by lilith** [comment]
Sorry for the slow response; if you don't get a response quickly on GitHub, please email support@imageresizing.net.

Thank you for the error report; you are exactly right.
