### ISSUE TITLE
Unable to serve image from a BlobProviderBase-derived class when no height or width specified

### ISSUE THREAD

**Issue by argimenes** [imazen/resizer#230]
In certain cases I don't need to resize an image but do make use of the plugin pipeline to perform authorisation on image access. In the case when I want to return the raw image from its virtual folder (out of the website path) the plugin throws an exception when no height, width, or maxwidth or maxheight values are specified.

**Comment by lilith** [comment]
You can use `&proccess=no&cache=always` instead of actually processing the image. But without the actual exception I can't help in debugging this.
