### ISSUE TITLE
Image404 open redirect vulnerability

### ISSUE THREAD

**Issue by jeroenk-channelengine** [imazen/resizer#237]
The image404 plugin is vulnerable to open redirect. It correctly catches values starting with http, but not with //. It will redirect to another site if someone uses 404=//example.com.

**For example:**

_Configuration:_
`<image404` default="~/content/img/default.png" />`

_Test:_
`<img src="default.png?404=//nu.nl"/>`

_Potential fix:_
In resolve404Path :
`if (path.StartsWith("http", StringComparison.OrdinalIgnoreCase)) throw new ImageProcessingException("Image 404 redirects must be server-local. Received " + path);`

change to:
`if (path.StartsWith("http", StringComparison.OrdinalIgnoreCase) || path.StartsWith("//")) throw new ImageProcessingException("Image 404 redirects must be server-local. Received " + path);`

**Comment by lilith** [comment]
Thank you for reporting this.

Could you open a PR with this change? I am AFK but would like to release the update today.

**Comment by christiaanderidder** [comment]
Hi @lilith, please see pull request #238
