### ISSUE TITLE
DiskCache plugin - Directory

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [imazen/resizer#245]
Normally we would do like the following:
`<diskcache dir="~/myfolder/ImageResizer" />`

We have a use case where the folder is above the website and we need to set the path at runtime.
Where/how would I be able to set that?

`ImageBuilder.Current.Build` is an option versus the normal middleware (if that helps anything).

Thanks in advance!

**Comment by OpenSpacesAndPlaces** [comment]
Two other notes on this:

`<diskcache dir="../parentfolder/myfolder/ImageResizer" />` results in:
Cannot use a leading .. to exit above the top directory.'

I also tried:
`Config.Current.Plugins.Get<DiskCache>().PhysicalCacheDir`

But is only coded as a get off of:
`VirtualCacheDir`

In theory I could copy the source-code, customize that one bit,  and add it as a plugin, but that seems extreme.

**Comment by OpenSpacesAndPlaces** [comment]
@lilith

**Comment by OpenSpacesAndPlaces** [comment]
I gave the custom plugin route a try, but for some reason `ImageBuilder.Current.Build` doesn't seem to use it.

Doing either:
```
mdc = new MyCustomDiskCache(mypath);
mdc.Install(Config.Current);
```

Or 
`<add name="MyNameSpace.MyCustomDiskCache" />`

`GetIssues` is clean.

Nor does this help:
```
 NoCache nc = Config.Current.Plugins.Get<NoCache>();
        if (nc != null)
            Config.Current.Plugins.remove_plugin(nc);
```
Images are all loading and modified correctly - it's just not disk caching at all.

Otherwise everything seems to look Ok in: `Config.Current.Plugins`

**Comment by lilith** [comment]
You'll need to use an IIS virtual directory for security reasons if you want it outside the app folder.

**Comment by OpenSpacesAndPlaces** [comment]
> You'll need to use an IIS virtual directory for security reasons if you want it outside the app folder.

There's no work around of any kind?
We running our image requests fully managed via an in-code httpmodule and have full control over what filetypes are even getting by.

Right now my only issue is that "ImageBuilder.Current.Build" seems to ignore the "DiskCache" plugin. 

Is there some security check inside "ImageBuilder.Current.Build" that disallows "unsecure" folders?
If so, can it be overridden somehow?

**Comment by lilith** [comment]
Not for DiskCache. It lets IIS serve the files. Using a out-of-site cache
folder is bad because all the security checks are bypassed.
