### ISSUE TITLE
Takes 100+ seconds to process images after Azure App Service slot swap

### ISSUE THREAD

**Issue by ajbeaven** [imazen/resizer#248]
I'm running ImageResizer on a Azure App Service with the DiskCache and AzureReader2 plugins installed as well as Cloudfront sitting in front of it providing an additional cache. The files created by DiskCache sit on the App Service's disk.

Most of the time this works fine; images load within 8-30ms and the world is good. Unfortunately, when I push a new update to this App Service (using slot swapping) and visit an image gallery of sorts (~36 photos on the page), everything grinds to a halt and requests for new images start taking more than 100+ seconds and I start receiving a few of these errors:

```
ImageResizer.ImageProcessingException: Failed to acquire a lock on file "D:\home\site\wwwroot\Content\images\cache\10f2\1471ec44e5dcc2ff5221d0111becd2a5a90af8177324acfa284744e510a786f2.jpg" within 15000ms. Caching failed.
```

I don't know why I'd receive the error above. More broadly though, I'm guessing the slow down occurs because ImageResizer can't find the DiskCache cached image in the newly swapped slot and so has to reprocess the images. I'm guessing it should take less than 100s to reprocess the images again though!

Looking at resizer.debug I see this error, though I'm not sure if it's relevant:
```
(Warning):	An external process indicates it is managing cleanup of the disk cache. This process is not currently managing disk cache cleanup. If configured as a web garden, keep in mind that the negligible performance gains are likely to be outweighed by the loss of cache optimization quality.
```

My web.config resizer section is below, I'm running on **version 4.2.5.1116** and at present the cache folder is around ~60GB in size.
```
<resizer>
    <pipeline defaultCommands="autorotate.default=true" />
    <plugins>
        <add name="Watermark" />
        <add name="DiskCache" />
        <add name="AzureReader2" prefix="~/azure" connectionString="[redacted]" redirectToBlobIfUnmodified="false" />
    </plugins>
    <diskcache dir="~/Content/images/cache" autoClean="true" />
    <clientcache minutes="1440" />
    <watermarks>
        <image name="logo-watermark" path="~/Content/images/image-watermark.png" bottom="2%" right="2%" width="60%" relativeTo="canvas" />
    </watermarks>
    <licenses>
        <license>
            [redacted]
        </license>
    </licenses>
</resizer>
```

Can you provide any insight here @lilith? Should ImageResizer work OK being set up on Azure like I have it? Is there anything in this slot swapping process that might cause ImageResizer to choke?

**Comment by ajbeaven** [comment]
OK, I think this is potentially related to DiskCache making changes which cause the application to be restarted. Here are some events that appear immediately post slot swap:

![Inkedunnamed_LI](https://user-images.githubusercontent.com/657201/66277251-2ada6500-e8f8-11e9-866e-f42e0cab457b.jpg)

Could these restarts be caused by the autoclean process? These sorts of 'global config' changes and app restarts appear to last for hours after the slot swap completes.

**Comment by lilith** [comment]
I thought we resolved this over email but I may have confused you with someone else. You'll want to disable fncmode per these instructions: https://imageresizing.net/docs/fcnmode

**Comment by ajbeaven** [comment]
Must have been someone else, haven't received an email on this sorry. Seriously, if this simple change resolves this issue you will make my freaking year. Will try it out and let you know.

**Comment by ajbeaven** [comment]
I've disabled ftcMode but unfortunately it did not affect the post-slot swap performance. 

Note that the instructions you linked to mentioned a specific error message that I've never actually received. 

Sorry I also forgot to mention in my original report that the performance issues are only apparent for around 30 minutes immediately after the slot swap. After that time, everything runs smoothly:

![image](https://user-images.githubusercontent.com/657201/84223961-756b4b80-ab2f-11ea-937b-7ffe213e231d.png)

**Comment by lilith** [comment]
```
ImageResizer.ImageProcessingException: Failed to acquire a lock on file "D:\home\site\wwwroot\Content\images\cache\10f2\1471ec44e5dcc2ff5221d0111becd2a5a90af8177324acfa284744e510a786f2.jpg" within 15000ms. Caching failed.
```
^ This error message means that there were duplicate requests for the same image variant, and that one of those requests took more than 15s to fulfill, which is excessive. Usually this indicates contention on the underlying file. 

```
(Warning):	An external process indicates it is managing cleanup of the disk cache. This process is not currently managing disk cache cleanup. If configured as a web garden, keep in mind that the negligible performance gains are likely to be outweighed by the loss of cache optimization quality.
```
^ This error message means that you have more than one instance of ImageResizer running, which can cause file lock problems such as with the first error. 

Application restarts can cause overlapping instances which can in turn cause more problems. We need to prevent the disk cache from triggering configuration change detection. Since autoClean does not delete folders, it seems likely that the *creation* of new folders is the problem. 

This is abnormal for IIS, and must be something Azure-specific. I would be curious to know if setting `WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG=1` made a difference, as it is supposed to prevent recycling when storage changes. 

The other option would be to move you to [Imageflow.Server](https://github.com/imazen/imageflow-dotnet-server) and use a cache folder outside of the app root. We don't yet have URL-based watermarking ready yet - are you using that feature extensively?

**Comment by ajbeaven** [comment]
I already had `WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG=1` set on both slots.

Yes we do use watermarking extensively. It's unfortunately a must-have requirement in our context.

Anything further I could provide that would help in diagnosing? I have a memory dump lying around that was taken over one of these periods. It may not tell you figure out much more than what you've already surmised, but I can email that through if you wanted?

**Comment by lilith** [comment]
I'll try to add watermark support tomorrow and then we should support
everthing I see in your config. You treat blobs as immutable, right?

**Comment by ajbeaven** [comment]
Wow, that'd be great! Yep, immutable blobs.

Just so I have this straight, I would be deploying a new .NET Core app (Imageflow app) with Imageflow.Server nuget package installed whose only job would be to handle image requests sent from my .NET Framework app (website). Why is it that the Imageflow app needs to maintain its image cache outside of the root app given it won't be involved in the deployment process for the website? Or would this not be necessary if I have a standalone Imageflow app?

**Comment by lilith** [comment]
Correct. It needs to be outside the root so it doesn't trigger Azure's
configuration watcher and thereby cause 30 mins of recycles.

**Comment by lilith** [comment]
Okay, so I think everything is feature-complete for you: 

https://github.com/imazen/imageflow-dotnet-server

Email me at support@imazen.io and I'll send you my phone number in case you run into any problems and need a faster turn-around time.

**Comment by ajbeaven** [comment]
Thanks so much for this. What an excellent turn around.

As an aside, couldn't I have just put the image cache for ImageResizer v4 outside of the app root which would have the same effect? Or does the older version of DiskCache not work with absolute paths?

**Comment by lilith** [comment]
ImageResizer relies on the StaticFileHandler to serve all disk files efficiently and SFH can't serve files outside of the app root :(

**Comment by lilith** [comment]
We resolved this with Imageflow.NET Server.
