### ISSUE TITLE
Origin of https://github.com/imazen/resizer/blob/develop/Plugins/Wic/InteropServices/PropVariant.cs

### ISSUE THREAD

**Issue by atlastodor** [imazen/resizer#249]
I am trying to figure out where the sources in this [file](https://github.com/imazen/resizer/blob/develop/Plugins/Wic/InteropServices/PropVariant.cs) originated. The original of the file has "Copyright (c) Microsoft Corporation. All rights reserved." with a very permissive license (which was later changed an Imazen LLC license). I suspect this was a part of an MSDN code sample, probably "Windows Imaging Component (WIC) Tools".

We have a copy of the same code, and during a review for our migration to 64-bit, we discovered that the UnmanagedPropVariant struct may be badly defined. I want to see if there is an updated version of the file from the original publisher.

Thanks.

**Comment by lilith** [comment]
Yes, it was an MSDN code sample at one point. I'm not aware of a source that is updated. I would definitely be interested if you find one.
