### ISSUE TITLE
Difficult to get WebP to run: 1st because of C Distributables

### ISSUE THREAD

**Issue by iJungleboy** [imazen/resizer#257]
I wanted to share this for others having this problem, or for @lilith who may find another better way to solve this, also in light of the much anticipated ImageFlow.

We make a Plugin for DNN called [2sxc](https://2sxc.org). It is actually a bundle of plugins, one of which is a [DNN wrapper containing the resizer](https://github.com/2sic/dnn-imazen-imageresizer). The latest version of the wrapper now automatically enables WebP support. 

When we got done developing it, we deployed it on various servers - some of which worked, and others simply failed. After many hours of research we found 2 issues - here's #1 ([see 2nd here](258)):

## WebP Requires the Web Server to have C Redistributables installed

You can get them [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) but this was very difficult for us to figure out (no useful errors) and on some of our "cleaner" servers this was missing. 

It also feels like "nasty overhead" just to get another image format to work. 

How to resolve: not really sure, but it would surely help if the libwebp.dll either contained all it's dependencies, or was a .net library. The .net library would also be better because of the second issue I'll describe next.

**Comment by lilith** [comment]
Unfortunately, it's not likely there will ever be a native C# library for decoding and encoding WebP. 

The C Runtime is also not (for security reasons) something we'd want to embed in the .dll. It should be delivered over Windows Update.

The Universal CRT should be supported in newer builds of webp. This should automatically be present on windows machines that have been updated.
