### ISSUE TITLE
Wrong colors after resizing

### ISSUE THREAD

**Issue by HRasch** [imazen/resizer#276]
Hello, 
I have trouble on resizing some pictures. The background suddenly gets pink or black. It seems to depend on the DPI or resolution. After resizing / saving the pics with another Image-Software, the pictures can be resized correctly.
![5015fada764140168d4a39ee0a162ad9](https://user-images.githubusercontent.com/23297306/178800139-fd04af8f-68f8-4599-9e03-c12f0d7690d6.jpg)
![93a6084109364003ae6ed8f9bdf56823](https://user-images.githubusercontent.com/23297306/178800144-cab3b7cd-6f29-4ac8-bfa3-e490aa23b67b.jpg)

**Comment by lilith** [comment]
Can you provide the code or URL/query that causes this to occur? I need to be able to reproduce it.

**Comment by lilith** [comment]
Also, please include the version of imageflow.dll or imageflow_tool

**Comment by HRasch** [comment]
This happens on the latestest version of imageresizing.net. I use here the http-module in an asp.net mvc application.

**Comment by HRasch** [comment]
Sorry, i saw the requested images are already fixed. Here are some 'invalid' ones
![ksb_d_29121](https://user-images.githubusercontent.com/23297306/181047078-099a3696-9e01-406b-9a07-73f3bafb7c37.jpg)

https://eshop.eisen-pfeiffer.de/media/Sonstiges/ksb_d_29121.jpg?w=300

**Comment by lilith** [comment]
Can you email the unmodified / messed up images to ***@***.*** and
separately what you're getting from ImageResizer? I also need your
/resizer.debug page.

**Comment by lilith** [comment]
It looks like the Windows APIs that ImageResizer 4.x uses cannot properly handle these. 

ImageResizer 5 works fine using the Imageflow backend, though. Would you be interested in helping alpha test v5?

**Comment by ArjendeMooij-KatanaPIM** [comment]
> It looks like the Windows APIs that ImageResizer 4.x uses cannot properly handle these.
> 
> ImageResizer 5 works fine using the Imageflow backend, though. Would you be interested in helping alpha test v5?

We're dealing with the same issue. You say that "ImageResizer 4.x uses cannot properly handle these.". What is special with these images that it doesn't support this? Because then at least I can tell our clients how to work arount it.

**Comment by HRasch** [comment]
> > It looks like the Windows APIs that ImageResizer 4.x uses cannot properly handle these.
> > ImageResizer 5 works fine using the Imageflow backend, though. Would you be interested in helping alpha test v5?
> 
> We're dealing with the same issue. You say that "ImageResizer 4.x uses cannot properly handle these.". What is special with these images that it doesn't support this? Because then at least I can tell our clients how to work arount it.

I have still trouble with this in Version 4. I noticed this images may have a unusual high dpi. Lilith may have details about the error, she fixed it on imageflow I guess.

**Comment by lilith** [comment]
Can you try the v5 prerelease with the Imageflow plugin?
