### ISSUE TITLE
AzureReader2 should add connection string to web.config

### ISSUE THREAD

**Issue by MisinformedDNA** [imazen/resizer#41]
When AzureReader2 is added via NuGet, the development connection string should automatically be added. Potentially, a commented example of the non-development version should be included as well.

If there is no web.config/app.config, I think that it creates one. I think Entity Framework is set up like that. If it's going in a library, then they will need it somewhere, so they can easily copy it from there.

This makes it easier for people to get started and not have to go in search of documentation.

NOTE: This would apply to all similar plugins, but I haven't verified the rest.

**Comment by lilith** [comment]
NuGet packages should avoid this kind of behavior.
