### ISSUE TITLE
Add async stream parser for image width, height, depth, & frame/page count.

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/resizer#63]
It is fundamentally impossible to calculate the optimal operation sequence (and therefore the optimal pipeline) until we know the characteristics of the source image. 

Our greatest chance for massive perf improvements is during jpeg decoding, where we can scale in multiples of 2 very efficiently. We can't calculate what scale factor is appropriate without knowing the source size (and destination).

Of course, we can't implement parsing for every potential format, so we will have to fall back to an inefficient path.

Initial support for Jpeg, Gif, Png, and Tiff would be best.

**Comment by lilith** [comment]
Somewhat implemented in https://github.com/imazen/imageflow
